# Published by dynamixel_workbench_single_manager and Subscribed by dynamixel_workbench_single_manager_gui
# This message is compatible with control table of Dynamixel XM Series (XM430-S210-R, XM430-W350-R)
# and it is linked to XM430_W210_R.device and XM430_S350_R.device in dynamixel_workbench_toolbox/dynamixel/XM folder
# If you want to specific information about control table, please follow the link (http://support.robotis.com/en/)

int64 model_number
int64 version_of_firmware
int8  id
int64 baud_rate
int64 return_delay_time
int64 operating_mode
int64 protocol_version
int64 homing_offset
int64 moving_threshold
int64 max_temperature_limit
int64 max_voltage_limit
int64 min_voltage_limit
int64 pwm_limit
int64 current_limit
int64 acceleration_limit
int64 velocity_limit
int64 max_position_limit
int64 min_position_limit
int64 shutdown
bool  torque_enable
bool led
int64 status_return_level
int64 registered_instruction
int64 hardware_error_status
int64 velocity_i_gain
int64 velocity_p_gain
int64 position_d_gain
int64 position_i_gain
int64 position_p_gain
int64 feedforward_2nd_gain
int64 feedforward_1st_gain
int64 goal_pwm
int64 goal_current
int64 goal_velocity
int64 profile_acceleration
int64 profile_velocity
int64 goal_position
int64 realtime_tick
bool moving
int64 moving_status
int64 present_pwm
int64 present_current
int64 present_velocity
int64 present_position
int64 velocity_trajectory
int64 position_trajectory
int64 present_input_voltage
int64 present_temperature
