# Published by dynamixel_workbench_single_manager and Subscribed by dynamixel_workbench_single_manager_gui
# This message is compatible with control table of Dynamixel EX Series (EX-106+)
# and it is linked to EX_106.device in dynamixel_workbench_toolbox/dynamixel/EX folder
# If you want to specific information about control table, please follow the link (http://support.robotis.com/en/)

int64 model_number
int64 version_of_firmware
int8 id
int64 baud_rate
int64 return_delay_time
int64 cw_angle_limit
int64 ccw_angle_limit
int64 drive_mode
int64 the_highest_limit_temperature
int64 the_lowest_limit_voltage
int64 the_highest_limit_voltage
int64 max_torque
int64 status_return_level
int64 alarm_led
int64 alarm_shutdown
bool torque_enable
bool led
int64 cw_compliance_margin
int64 ccw_compliance_margin
int64 cw_compliance_slope
int64 ccw_compliance_slope
int64 goal_position
int64 moving_speed
int64 torque_limit
int64 present_position
int64 present_velocity
int64 present_load
int64 present_voltage
int64 present_temperature
bool registered
bool moving
bool lock
int64 punch
int64 sensed_current
