# Published by dynamixel_workbench_single_manager and Subscribed by dynamixel_workbench_single_manager_gui
# This message is compatible with control table of Dynamixel Pro Series
# (L54-30-S500-R, L54-30-S400-R, L54-50-S500-R, L54-50-S290-R,
#  M42-10-S260-R, M54-40-S250-R, M54-60-S250-R,
#  H42-20-S300-R, H54-100-S500-R, H54-200-S500-R)
# and it is linked to PRO_L54_30_S500_R.device, PRO_L54_30_S400_R.device, PRO_L54_50_S500_R.device, PRO_L54_50_S290_R.device,
#                     PRO_M42_10_S260_R.device, PRO_M54_40_S250_R.device, PRO_M54_60_S250_R.device
#                     PRO_H42_20_S300_R.device, PRO_H54_100_S500_R.device and PRO_H54_200_S500_R.device in dynamixel_workbench_toolbox/dynamixel/PR folder
# If you want to specific information about control table, please follow the link (http://support.robotis.com/en/)

int64 model_number
int64 version_of_firmware
int8  id
int64 baud_rate
int64 return_delay_time
int64 operating_mode
int64 homing_offset
int64 moving_threshold
int64 max_temperature_limit
int64 max_voltage_limit
int64 min_voltage_limit
int64 acceleration_limit
int64 torque_limit
int64 velocity_limit
int64 max_position_limit
int64 min_position_limit
int64 external_port_mod_1
int64 external_port_mod_2
int64 external_port_mod_3
int64 external_port_mod_4
int64 shutdown
int64 indirect_address_1
bool  torque_enable
int64 led_red
int64 led_green
int64 led_blue
int64 velocity_i_gain
int64 velocity_p_gain
int64 position_p_gain
int64 goal_position
int64 goal_velocity
int64 goal_torque
int64 goal_acceleration
bool is_moving
int64 present_position
int64 present_velocity
int64 present_current
int64 present_voltage
int64 present_temperature
int64 external_port_data_1
int64 external_port_data_2
int64 external_port_data_3
int64 external_port_data_4
int64 indirect_data_1
bool registered_instruction
int64 status_return_level
int64 hardware_error_status
