controller_manager:
  ros__parameters:
    update_rate: 50

    joint_state_broadcaster:
      type: joint_state_broadcaster/JointStateBroadcaster

    position_joint_trajectory_controller:
      type: joint_trajectory_controller/JointTrajectoryController

    joint_group_effort_controller:
      type: effort_controllers/JointGroupEffortController

position_joint_trajectory_controller:
  ros__parameters:
    joints:
      - sample_joint
    command_interfaces:
      - position
    state_interfaces:
      - position
      - velocity

joint_group_effort_controller:
  ros__parameters:
    joints:
      - sample_joint
    interface_name: effort
