joint_state_controller:
  type: joint_state_controller/JointStateController
  publish_rate: 20

joint_group_effort_controller:
  type: "effort_controllers/JointGroupEffortController"
  joints:
    - sample_joint
