sample_pan_motor:
  ID: 1
  torque_constant: 1.15
  Return_Delay_Time: 0
sample_tilt_motor:
  ID: 2
  torque_constant: 1.15
  Return_Delay_Time: 0
# Above torque_constant is an example value for XC330-T288-T: (Stall Torque [Nm]) / (Current at Stall Torque [A]) = 0.92 / 0.80
# You do not have to change that value when you just try this sample because that value have little influence on main topics of this sample.
# But when you apply dynamixel_general_hw to your robot, you may have to change this value in your yaml depending on your situation (e.g., you use a different actuator, a different torque constant value is good for your operation range)
