# You can find control table of Dynamixel on emanual (http://emanual.robotis.com/#control-table)
# Control table item has to be set Camel_Case and not included whitespace
# You are supposed to set at least Dynamixel ID
sample_motor:
  ID: 1
  torque_constant: 1.15  # Example value for XC330-T288-T with Protocol 2.0: (Stall Torque [Nm]) / (Current at Stall Torque [A]) = 0.92 / 0.80
  Return_Delay_Time: 0
