joint_state_controller:
  type: joint_state_controller/JointStateController
  publish_rate: 20

joint_group_velocity_controller:
  type: velocity_controllers/JointGroupVelocityController
  joints:
    - sample_joint
